// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: proto/gpuproxy.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GPUProxyService_Login_FullMethodName                   = "/gpuproxy.GPUProxyService/Login"
	GPUProxyService_CreateAPIKey_FullMethodName            = "/gpuproxy.GPUProxyService/CreateAPIKey"
	GPUProxyService_ListGPUInstances_FullMethodName        = "/gpuproxy.GPUProxyService/ListGPUInstances"
	GPUProxyService_CreateGPUInstance_FullMethodName       = "/gpuproxy.GPUProxyService/CreateGPUInstance"
	GPUProxyService_DestroyGPUInstance_FullMethodName      = "/gpuproxy.GPUProxyService/DestroyGPUInstance"
	GPUProxyService_GetGPUInstance_FullMethodName          = "/gpuproxy.GPUProxyService/GetGPUInstance"
	GPUProxyService_ProxyRequest_FullMethodName            = "/gpuproxy.GPUProxyService/ProxyRequest"
	GPUProxyService_StreamProxyRequest_FullMethodName      = "/gpuproxy.GPUProxyService/StreamProxyRequest"
	GPUProxyService_CreatePayment_FullMethodName           = "/gpuproxy.GPUProxyService/CreatePayment"
	GPUProxyService_GetTransactions_FullMethodName         = "/gpuproxy.GPUProxyService/GetTransactions"
	GPUProxyService_GetSpendingInfo_FullMethodName         = "/gpuproxy.GPUProxyService/GetSpendingInfo"
	GPUProxyService_CheckSpendingLimit_FullMethodName      = "/gpuproxy.GPUProxyService/CheckSpendingLimit"
	GPUProxyService_SetLoadBalancerStrategy_FullMethodName = "/gpuproxy.GPUProxyService/SetLoadBalancerStrategy"
	GPUProxyService_GetLoadInfo_FullMethodName             = "/gpuproxy.GPUProxyService/GetLoadInfo"
	GPUProxyService_ReserveGPUs_FullMethodName             = "/gpuproxy.GPUProxyService/ReserveGPUs"
	GPUProxyService_HealthCheck_FullMethodName             = "/gpuproxy.GPUProxyService/HealthCheck"
)

// GPUProxyServiceClient is the client API for GPUProxyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GPUProxyService provides GPU management and proxy functionality
type GPUProxyServiceClient interface {
	// Authentication
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	CreateAPIKey(ctx context.Context, in *CreateAPIKeyRequest, opts ...grpc.CallOption) (*CreateAPIKeyResponse, error)
	// GPU Management
	ListGPUInstances(ctx context.Context, in *ListGPUInstancesRequest, opts ...grpc.CallOption) (*ListGPUInstancesResponse, error)
	CreateGPUInstance(ctx context.Context, in *CreateGPUInstanceRequest, opts ...grpc.CallOption) (*CreateGPUInstanceResponse, error)
	DestroyGPUInstance(ctx context.Context, in *DestroyGPUInstanceRequest, opts ...grpc.CallOption) (*DestroyGPUInstanceResponse, error)
	GetGPUInstance(ctx context.Context, in *GetGPUInstanceRequest, opts ...grpc.CallOption) (*GetGPUInstanceResponse, error)
	// Proxy Requests
	ProxyRequest(ctx context.Context, in *ProxyRequestMessage, opts ...grpc.CallOption) (*ProxyResponse, error)
	StreamProxyRequest(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProxyRequestMessage, ProxyResponse], error)
	// Billing
	CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentResponse, error)
	GetTransactions(ctx context.Context, in *GetTransactionsRequest, opts ...grpc.CallOption) (*GetTransactionsResponse, error)
	// Guard Rails
	GetSpendingInfo(ctx context.Context, in *GetSpendingInfoRequest, opts ...grpc.CallOption) (*GetSpendingInfoResponse, error)
	CheckSpendingLimit(ctx context.Context, in *CheckSpendingLimitRequest, opts ...grpc.CallOption) (*CheckSpendingLimitResponse, error)
	// Load Balancing
	SetLoadBalancerStrategy(ctx context.Context, in *SetLoadBalancerStrategyRequest, opts ...grpc.CallOption) (*SetLoadBalancerStrategyResponse, error)
	GetLoadInfo(ctx context.Context, in *GetLoadInfoRequest, opts ...grpc.CallOption) (*GetLoadInfoResponse, error)
	ReserveGPUs(ctx context.Context, in *ReserveGPUsRequest, opts ...grpc.CallOption) (*ReserveGPUsResponse, error)
	// Health
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type gPUProxyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGPUProxyServiceClient(cc grpc.ClientConnInterface) GPUProxyServiceClient {
	return &gPUProxyServiceClient{cc}
}

func (c *gPUProxyServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, GPUProxyService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPUProxyServiceClient) CreateAPIKey(ctx context.Context, in *CreateAPIKeyRequest, opts ...grpc.CallOption) (*CreateAPIKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAPIKeyResponse)
	err := c.cc.Invoke(ctx, GPUProxyService_CreateAPIKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPUProxyServiceClient) ListGPUInstances(ctx context.Context, in *ListGPUInstancesRequest, opts ...grpc.CallOption) (*ListGPUInstancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGPUInstancesResponse)
	err := c.cc.Invoke(ctx, GPUProxyService_ListGPUInstances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPUProxyServiceClient) CreateGPUInstance(ctx context.Context, in *CreateGPUInstanceRequest, opts ...grpc.CallOption) (*CreateGPUInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGPUInstanceResponse)
	err := c.cc.Invoke(ctx, GPUProxyService_CreateGPUInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPUProxyServiceClient) DestroyGPUInstance(ctx context.Context, in *DestroyGPUInstanceRequest, opts ...grpc.CallOption) (*DestroyGPUInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroyGPUInstanceResponse)
	err := c.cc.Invoke(ctx, GPUProxyService_DestroyGPUInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPUProxyServiceClient) GetGPUInstance(ctx context.Context, in *GetGPUInstanceRequest, opts ...grpc.CallOption) (*GetGPUInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGPUInstanceResponse)
	err := c.cc.Invoke(ctx, GPUProxyService_GetGPUInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPUProxyServiceClient) ProxyRequest(ctx context.Context, in *ProxyRequestMessage, opts ...grpc.CallOption) (*ProxyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProxyResponse)
	err := c.cc.Invoke(ctx, GPUProxyService_ProxyRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPUProxyServiceClient) StreamProxyRequest(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProxyRequestMessage, ProxyResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GPUProxyService_ServiceDesc.Streams[0], GPUProxyService_StreamProxyRequest_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProxyRequestMessage, ProxyResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GPUProxyService_StreamProxyRequestClient = grpc.BidiStreamingClient[ProxyRequestMessage, ProxyResponse]

func (c *gPUProxyServiceClient) CreatePayment(ctx context.Context, in *CreatePaymentRequest, opts ...grpc.CallOption) (*CreatePaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePaymentResponse)
	err := c.cc.Invoke(ctx, GPUProxyService_CreatePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPUProxyServiceClient) GetTransactions(ctx context.Context, in *GetTransactionsRequest, opts ...grpc.CallOption) (*GetTransactionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTransactionsResponse)
	err := c.cc.Invoke(ctx, GPUProxyService_GetTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPUProxyServiceClient) GetSpendingInfo(ctx context.Context, in *GetSpendingInfoRequest, opts ...grpc.CallOption) (*GetSpendingInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSpendingInfoResponse)
	err := c.cc.Invoke(ctx, GPUProxyService_GetSpendingInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPUProxyServiceClient) CheckSpendingLimit(ctx context.Context, in *CheckSpendingLimitRequest, opts ...grpc.CallOption) (*CheckSpendingLimitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckSpendingLimitResponse)
	err := c.cc.Invoke(ctx, GPUProxyService_CheckSpendingLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPUProxyServiceClient) SetLoadBalancerStrategy(ctx context.Context, in *SetLoadBalancerStrategyRequest, opts ...grpc.CallOption) (*SetLoadBalancerStrategyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetLoadBalancerStrategyResponse)
	err := c.cc.Invoke(ctx, GPUProxyService_SetLoadBalancerStrategy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPUProxyServiceClient) GetLoadInfo(ctx context.Context, in *GetLoadInfoRequest, opts ...grpc.CallOption) (*GetLoadInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLoadInfoResponse)
	err := c.cc.Invoke(ctx, GPUProxyService_GetLoadInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPUProxyServiceClient) ReserveGPUs(ctx context.Context, in *ReserveGPUsRequest, opts ...grpc.CallOption) (*ReserveGPUsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveGPUsResponse)
	err := c.cc.Invoke(ctx, GPUProxyService_ReserveGPUs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPUProxyServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, GPUProxyService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GPUProxyServiceServer is the server API for GPUProxyService service.
// All implementations must embed UnimplementedGPUProxyServiceServer
// for forward compatibility.
//
// GPUProxyService provides GPU management and proxy functionality
type GPUProxyServiceServer interface {
	// Authentication
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	CreateAPIKey(context.Context, *CreateAPIKeyRequest) (*CreateAPIKeyResponse, error)
	// GPU Management
	ListGPUInstances(context.Context, *ListGPUInstancesRequest) (*ListGPUInstancesResponse, error)
	CreateGPUInstance(context.Context, *CreateGPUInstanceRequest) (*CreateGPUInstanceResponse, error)
	DestroyGPUInstance(context.Context, *DestroyGPUInstanceRequest) (*DestroyGPUInstanceResponse, error)
	GetGPUInstance(context.Context, *GetGPUInstanceRequest) (*GetGPUInstanceResponse, error)
	// Proxy Requests
	ProxyRequest(context.Context, *ProxyRequestMessage) (*ProxyResponse, error)
	StreamProxyRequest(grpc.BidiStreamingServer[ProxyRequestMessage, ProxyResponse]) error
	// Billing
	CreatePayment(context.Context, *CreatePaymentRequest) (*CreatePaymentResponse, error)
	GetTransactions(context.Context, *GetTransactionsRequest) (*GetTransactionsResponse, error)
	// Guard Rails
	GetSpendingInfo(context.Context, *GetSpendingInfoRequest) (*GetSpendingInfoResponse, error)
	CheckSpendingLimit(context.Context, *CheckSpendingLimitRequest) (*CheckSpendingLimitResponse, error)
	// Load Balancing
	SetLoadBalancerStrategy(context.Context, *SetLoadBalancerStrategyRequest) (*SetLoadBalancerStrategyResponse, error)
	GetLoadInfo(context.Context, *GetLoadInfoRequest) (*GetLoadInfoResponse, error)
	ReserveGPUs(context.Context, *ReserveGPUsRequest) (*ReserveGPUsResponse, error)
	// Health
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedGPUProxyServiceServer()
}

// UnimplementedGPUProxyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGPUProxyServiceServer struct{}

func (UnimplementedGPUProxyServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedGPUProxyServiceServer) CreateAPIKey(context.Context, *CreateAPIKeyRequest) (*CreateAPIKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAPIKey not implemented")
}
func (UnimplementedGPUProxyServiceServer) ListGPUInstances(context.Context, *ListGPUInstancesRequest) (*ListGPUInstancesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGPUInstances not implemented")
}
func (UnimplementedGPUProxyServiceServer) CreateGPUInstance(context.Context, *CreateGPUInstanceRequest) (*CreateGPUInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGPUInstance not implemented")
}
func (UnimplementedGPUProxyServiceServer) DestroyGPUInstance(context.Context, *DestroyGPUInstanceRequest) (*DestroyGPUInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DestroyGPUInstance not implemented")
}
func (UnimplementedGPUProxyServiceServer) GetGPUInstance(context.Context, *GetGPUInstanceRequest) (*GetGPUInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGPUInstance not implemented")
}
func (UnimplementedGPUProxyServiceServer) ProxyRequest(context.Context, *ProxyRequestMessage) (*ProxyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProxyRequest not implemented")
}
func (UnimplementedGPUProxyServiceServer) StreamProxyRequest(grpc.BidiStreamingServer[ProxyRequestMessage, ProxyResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamProxyRequest not implemented")
}
func (UnimplementedGPUProxyServiceServer) CreatePayment(context.Context, *CreatePaymentRequest) (*CreatePaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePayment not implemented")
}
func (UnimplementedGPUProxyServiceServer) GetTransactions(context.Context, *GetTransactionsRequest) (*GetTransactionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTransactions not implemented")
}
func (UnimplementedGPUProxyServiceServer) GetSpendingInfo(context.Context, *GetSpendingInfoRequest) (*GetSpendingInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSpendingInfo not implemented")
}
func (UnimplementedGPUProxyServiceServer) CheckSpendingLimit(context.Context, *CheckSpendingLimitRequest) (*CheckSpendingLimitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckSpendingLimit not implemented")
}
func (UnimplementedGPUProxyServiceServer) SetLoadBalancerStrategy(context.Context, *SetLoadBalancerStrategyRequest) (*SetLoadBalancerStrategyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetLoadBalancerStrategy not implemented")
}
func (UnimplementedGPUProxyServiceServer) GetLoadInfo(context.Context, *GetLoadInfoRequest) (*GetLoadInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLoadInfo not implemented")
}
func (UnimplementedGPUProxyServiceServer) ReserveGPUs(context.Context, *ReserveGPUsRequest) (*ReserveGPUsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReserveGPUs not implemented")
}
func (UnimplementedGPUProxyServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedGPUProxyServiceServer) mustEmbedUnimplementedGPUProxyServiceServer() {}
func (UnimplementedGPUProxyServiceServer) testEmbeddedByValue()                         {}

// UnsafeGPUProxyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GPUProxyServiceServer will
// result in compilation errors.
type UnsafeGPUProxyServiceServer interface {
	mustEmbedUnimplementedGPUProxyServiceServer()
}

func RegisterGPUProxyServiceServer(s grpc.ServiceRegistrar, srv GPUProxyServiceServer) {
	// If the following call panics, it indicates UnimplementedGPUProxyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GPUProxyService_ServiceDesc, srv)
}

func _GPUProxyService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPUProxyServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPUProxyService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPUProxyServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPUProxyService_CreateAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAPIKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPUProxyServiceServer).CreateAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPUProxyService_CreateAPIKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPUProxyServiceServer).CreateAPIKey(ctx, req.(*CreateAPIKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPUProxyService_ListGPUInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGPUInstancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPUProxyServiceServer).ListGPUInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPUProxyService_ListGPUInstances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPUProxyServiceServer).ListGPUInstances(ctx, req.(*ListGPUInstancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPUProxyService_CreateGPUInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGPUInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPUProxyServiceServer).CreateGPUInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPUProxyService_CreateGPUInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPUProxyServiceServer).CreateGPUInstance(ctx, req.(*CreateGPUInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPUProxyService_DestroyGPUInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyGPUInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPUProxyServiceServer).DestroyGPUInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPUProxyService_DestroyGPUInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPUProxyServiceServer).DestroyGPUInstance(ctx, req.(*DestroyGPUInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPUProxyService_GetGPUInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGPUInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPUProxyServiceServer).GetGPUInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPUProxyService_GetGPUInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPUProxyServiceServer).GetGPUInstance(ctx, req.(*GetGPUInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPUProxyService_ProxyRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProxyRequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPUProxyServiceServer).ProxyRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPUProxyService_ProxyRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPUProxyServiceServer).ProxyRequest(ctx, req.(*ProxyRequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPUProxyService_StreamProxyRequest_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GPUProxyServiceServer).StreamProxyRequest(&grpc.GenericServerStream[ProxyRequestMessage, ProxyResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GPUProxyService_StreamProxyRequestServer = grpc.BidiStreamingServer[ProxyRequestMessage, ProxyResponse]

func _GPUProxyService_CreatePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPUProxyServiceServer).CreatePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPUProxyService_CreatePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPUProxyServiceServer).CreatePayment(ctx, req.(*CreatePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPUProxyService_GetTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPUProxyServiceServer).GetTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPUProxyService_GetTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPUProxyServiceServer).GetTransactions(ctx, req.(*GetTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPUProxyService_GetSpendingInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSpendingInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPUProxyServiceServer).GetSpendingInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPUProxyService_GetSpendingInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPUProxyServiceServer).GetSpendingInfo(ctx, req.(*GetSpendingInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPUProxyService_CheckSpendingLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckSpendingLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPUProxyServiceServer).CheckSpendingLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPUProxyService_CheckSpendingLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPUProxyServiceServer).CheckSpendingLimit(ctx, req.(*CheckSpendingLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPUProxyService_SetLoadBalancerStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLoadBalancerStrategyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPUProxyServiceServer).SetLoadBalancerStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPUProxyService_SetLoadBalancerStrategy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPUProxyServiceServer).SetLoadBalancerStrategy(ctx, req.(*SetLoadBalancerStrategyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPUProxyService_GetLoadInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLoadInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPUProxyServiceServer).GetLoadInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPUProxyService_GetLoadInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPUProxyServiceServer).GetLoadInfo(ctx, req.(*GetLoadInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPUProxyService_ReserveGPUs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveGPUsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPUProxyServiceServer).ReserveGPUs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPUProxyService_ReserveGPUs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPUProxyServiceServer).ReserveGPUs(ctx, req.(*ReserveGPUsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPUProxyService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPUProxyServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPUProxyService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPUProxyServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GPUProxyService_ServiceDesc is the grpc.ServiceDesc for GPUProxyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GPUProxyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gpuproxy.GPUProxyService",
	HandlerType: (*GPUProxyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _GPUProxyService_Login_Handler,
		},
		{
			MethodName: "CreateAPIKey",
			Handler:    _GPUProxyService_CreateAPIKey_Handler,
		},
		{
			MethodName: "ListGPUInstances",
			Handler:    _GPUProxyService_ListGPUInstances_Handler,
		},
		{
			MethodName: "CreateGPUInstance",
			Handler:    _GPUProxyService_CreateGPUInstance_Handler,
		},
		{
			MethodName: "DestroyGPUInstance",
			Handler:    _GPUProxyService_DestroyGPUInstance_Handler,
		},
		{
			MethodName: "GetGPUInstance",
			Handler:    _GPUProxyService_GetGPUInstance_Handler,
		},
		{
			MethodName: "ProxyRequest",
			Handler:    _GPUProxyService_ProxyRequest_Handler,
		},
		{
			MethodName: "CreatePayment",
			Handler:    _GPUProxyService_CreatePayment_Handler,
		},
		{
			MethodName: "GetTransactions",
			Handler:    _GPUProxyService_GetTransactions_Handler,
		},
		{
			MethodName: "GetSpendingInfo",
			Handler:    _GPUProxyService_GetSpendingInfo_Handler,
		},
		{
			MethodName: "CheckSpendingLimit",
			Handler:    _GPUProxyService_CheckSpendingLimit_Handler,
		},
		{
			MethodName: "SetLoadBalancerStrategy",
			Handler:    _GPUProxyService_SetLoadBalancerStrategy_Handler,
		},
		{
			MethodName: "GetLoadInfo",
			Handler:    _GPUProxyService_GetLoadInfo_Handler,
		},
		{
			MethodName: "ReserveGPUs",
			Handler:    _GPUProxyService_ReserveGPUs_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _GPUProxyService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamProxyRequest",
			Handler:       _GPUProxyService_StreamProxyRequest_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/gpuproxy.proto",
}
