// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/gpuproxy.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Authentication Messages
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_gpuproxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpuproxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_gpuproxy_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_gpuproxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpuproxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_gpuproxy_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LoginResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CreateAPIKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"` // JWT token for auth
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAPIKeyRequest) Reset() {
	*x = CreateAPIKeyRequest{}
	mi := &file_proto_gpuproxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAPIKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAPIKeyRequest) ProtoMessage() {}

func (x *CreateAPIKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpuproxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAPIKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateAPIKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_gpuproxy_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAPIKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAPIKeyRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CreateAPIKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAPIKeyResponse) Reset() {
	*x = CreateAPIKeyResponse{}
	mi := &file_proto_gpuproxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAPIKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAPIKeyResponse) ProtoMessage() {}

func (x *CreateAPIKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpuproxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAPIKeyResponse.ProtoReflect.Descriptor instead.
func (*CreateAPIKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_gpuproxy_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAPIKeyResponse) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *CreateAPIKeyResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAPIKeyResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// GPU Instance Messages
type ListGPUInstancesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"` // "vast.ai", "io.net", or "all"
	MinVram       float64                `protobuf:"fixed64,2,opt,name=min_vram,json=minVram,proto3" json:"min_vram,omitempty"`
	MaxPrice      float64                `protobuf:"fixed64,3,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	GpuModel      string                 `protobuf:"bytes,4,opt,name=gpu_model,json=gpuModel,proto3" json:"gpu_model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGPUInstancesRequest) Reset() {
	*x = ListGPUInstancesRequest{}
	mi := &file_proto_gpuproxy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGPUInstancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGPUInstancesRequest) ProtoMessage() {}

func (x *ListGPUInstancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpuproxy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGPUInstancesRequest.ProtoReflect.Descriptor instead.
func (*ListGPUInstancesRequest) Descriptor() ([]byte, []int) {
	return file_proto_gpuproxy_proto_rawDescGZIP(), []int{4}
}

func (x *ListGPUInstancesRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ListGPUInstancesRequest) GetMinVram() float64 {
	if x != nil {
		return x.MinVram
	}
	return 0
}

func (x *ListGPUInstancesRequest) GetMaxPrice() float64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *ListGPUInstancesRequest) GetGpuModel() string {
	if x != nil {
		return x.GpuModel
	}
	return ""
}

type GPUInstance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	PricePerHour  float64                `protobuf:"fixed64,4,opt,name=price_per_hour,json=pricePerHour,proto3" json:"price_per_hour,omitempty"`
	VramGb        int32                  `protobuf:"varint,5,opt,name=vram_gb,json=vramGb,proto3" json:"vram_gb,omitempty"`
	GpuModel      string                 `protobuf:"bytes,6,opt,name=gpu_model,json=gpuModel,proto3" json:"gpu_model,omitempty"`
	NumGpus       int32                  `protobuf:"varint,7,opt,name=num_gpus,json=numGpus,proto3" json:"num_gpus,omitempty"`
	Location      string                 `protobuf:"bytes,8,opt,name=location,proto3" json:"location,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPUInstance) Reset() {
	*x = GPUInstance{}
	mi := &file_proto_gpuproxy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUInstance) ProtoMessage() {}

func (x *GPUInstance) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpuproxy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUInstance.ProtoReflect.Descriptor instead.
func (*GPUInstance) Descriptor() ([]byte, []int) {
	return file_proto_gpuproxy_proto_rawDescGZIP(), []int{5}
}

func (x *GPUInstance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GPUInstance) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *GPUInstance) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GPUInstance) GetPricePerHour() float64 {
	if x != nil {
		return x.PricePerHour
	}
	return 0
}

func (x *GPUInstance) GetVramGb() int32 {
	if x != nil {
		return x.VramGb
	}
	return 0
}

func (x *GPUInstance) GetGpuModel() string {
	if x != nil {
		return x.GpuModel
	}
	return ""
}

func (x *GPUInstance) GetNumGpus() int32 {
	if x != nil {
		return x.NumGpus
	}
	return 0
}

func (x *GPUInstance) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *GPUInstance) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ListGPUInstancesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instances     []*GPUInstance         `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGPUInstancesResponse) Reset() {
	*x = ListGPUInstancesResponse{}
	mi := &file_proto_gpuproxy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGPUInstancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGPUInstancesResponse) ProtoMessage() {}

func (x *ListGPUInstancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpuproxy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGPUInstancesResponse.ProtoReflect.Descriptor instead.
func (*ListGPUInstancesResponse) Descriptor() ([]byte, []int) {
	return file_proto_gpuproxy_proto_rawDescGZIP(), []int{6}
}

func (x *ListGPUInstancesResponse) GetInstances() []*GPUInstance {
	if x != nil {
		return x.Instances
	}
	return nil
}

func (x *ListGPUInstancesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type CreateGPUInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Env           map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Ports         []int32                `protobuf:"varint,5,rep,packed,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGPUInstanceRequest) Reset() {
	*x = CreateGPUInstanceRequest{}
	mi := &file_proto_gpuproxy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGPUInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGPUInstanceRequest) ProtoMessage() {}

func (x *CreateGPUInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpuproxy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGPUInstanceRequest.ProtoReflect.Descriptor instead.
func (*CreateGPUInstanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_gpuproxy_proto_rawDescGZIP(), []int{7}
}

func (x *CreateGPUInstanceRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CreateGPUInstanceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *CreateGPUInstanceRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CreateGPUInstanceRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *CreateGPUInstanceRequest) GetPorts() []int32 {
	if x != nil {
		return x.Ports
	}
	return nil
}

type CreateGPUInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGPUInstanceResponse) Reset() {
	*x = CreateGPUInstanceResponse{}
	mi := &file_proto_gpuproxy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGPUInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGPUInstanceResponse) ProtoMessage() {}

func (x *CreateGPUInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpuproxy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGPUInstanceResponse.ProtoReflect.Descriptor instead.
func (*CreateGPUInstanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_gpuproxy_proto_rawDescGZIP(), []int{8}
}

func (x *CreateGPUInstanceResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *CreateGPUInstanceResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CreateGPUInstanceResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateGPUInstanceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DestroyGPUInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyGPUInstanceRequest) Reset() {
	*x = DestroyGPUInstanceRequest{}
	mi := &file_proto_gpuproxy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyGPUInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyGPUInstanceRequest) ProtoMessage() {}

func (x *DestroyGPUInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpuproxy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyGPUInstanceRequest.ProtoReflect.Descriptor instead.
func (*DestroyGPUInstanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_gpuproxy_proto_rawDescGZIP(), []int{9}
}

func (x *DestroyGPUInstanceRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *DestroyGPUInstanceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type DestroyGPUInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyGPUInstanceResponse) Reset() {
	*x = DestroyGPUInstanceResponse{}
	mi := &file_proto_gpuproxy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyGPUInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyGPUInstanceResponse) ProtoMessage() {}

func (x *DestroyGPUInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpuproxy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyGPUInstanceResponse.ProtoReflect.Descriptor instead.
func (*DestroyGPUInstanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_gpuproxy_proto_rawDescGZIP(), []int{10}
}

func (x *DestroyGPUInstanceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DestroyGPUInstanceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetGPUInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGPUInstanceRequest) Reset() {
	*x = GetGPUInstanceRequest{}
	mi := &file_proto_gpuproxy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGPUInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGPUInstanceRequest) ProtoMessage() {}

func (x *GetGPUInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpuproxy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGPUInstanceRequest.ProtoReflect.Descriptor instead.
func (*GetGPUInstanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_gpuproxy_proto_rawDescGZIP(), []int{11}
}

func (x *GetGPUInstanceRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *GetGPUInstanceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type GetGPUInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *GPUInstance           `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGPUInstanceResponse) Reset() {
	*x = GetGPUInstanceResponse{}
	mi := &file_proto_gpuproxy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGPUInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGPUInstanceResponse) ProtoMessage() {}

func (x *GetGPUInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpuproxy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGPUInstanceResponse.ProtoReflect.Descriptor instead.
func (*GetGPUInstanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_gpuproxy_proto_rawDescGZIP(), []int{12}
}

func (x *GetGPUInstanceResponse) GetInstance() *GPUInstance {
	if x != nil {
		return x.Instance
	}
	return nil
}

// Proxy Messages
type ProxyRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"` // "http", "https", "mcp", "openinference"
	TargetUrl     string                 `protobuf:"bytes,2,opt,name=target_url,json=targetUrl,proto3" json:"target_url,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"` // HTTP method
	Headers       map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Timeout       int32                  `protobuf:"varint,6,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyRequestMessage) Reset() {
	*x = ProxyRequestMessage{}
	mi := &file_proto_gpuproxy_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyRequestMessage) ProtoMessage() {}

func (x *ProxyRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpuproxy_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyRequestMessage.ProtoReflect.Descriptor instead.
func (*ProxyRequestMessage) Descriptor() ([]byte, []int) {
	return file_proto_gpuproxy_proto_rawDescGZIP(), []int{13}
}

func (x *ProxyRequestMessage) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ProxyRequestMessage) GetTargetUrl() string {
	if x != nil {
		return x.TargetUrl
	}
	return ""
}

func (x *ProxyRequestMessage) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ProxyRequestMessage) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ProxyRequestMessage) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ProxyRequestMessage) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type ProxyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyResponse) Reset() {
	*x = ProxyResponse{}
	mi := &file_proto_gpuproxy_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyResponse) ProtoMessage() {}

func (x *ProxyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpuproxy_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyResponse.ProtoReflect.Descriptor instead.
func (*ProxyResponse) Descriptor() ([]byte, []int) {
	return file_proto_gpuproxy_proto_rawDescGZIP(), []int{14}
}

func (x *ProxyResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ProxyResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ProxyResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ProxyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Billing Messages
type CreatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Provider      string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`                                // "stripe", "crypto", "afterdark"
	PaymentMethod string                 `protobuf:"bytes,4,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"` // card:num:expr:ccv or crypto:network:wallet
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_proto_gpuproxy_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpuproxy_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_gpuproxy_proto_rawDescGZIP(), []int{15}
}

func (x *CreatePaymentRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePaymentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreatePaymentRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CreatePaymentRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

type CreatePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentResponse) Reset() {
	*x = CreatePaymentResponse{}
	mi := &file_proto_gpuproxy_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentResponse) ProtoMessage() {}

func (x *CreatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpuproxy_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_gpuproxy_proto_rawDescGZIP(), []int{16}
}

func (x *CreatePaymentResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *CreatePaymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreatePaymentResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePaymentResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type GetTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsRequest) Reset() {
	*x = GetTransactionsRequest{}
	mi := &file_proto_gpuproxy_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsRequest) ProtoMessage() {}

func (x *GetTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpuproxy_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_gpuproxy_proto_rawDescGZIP(), []int{17}
}

func (x *GetTransactionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetTransactionsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_proto_gpuproxy_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpuproxy_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_proto_gpuproxy_proto_rawDescGZIP(), []int{18}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Transaction) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Transaction) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Transaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Transaction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsResponse) Reset() {
	*x = GetTransactionsResponse{}
	mi := &file_proto_gpuproxy_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsResponse) ProtoMessage() {}

func (x *GetTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpuproxy_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_gpuproxy_proto_rawDescGZIP(), []int{19}
}

func (x *GetTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *GetTransactionsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// Guard Rails Messages
type GetSpendingInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpendingInfoRequest) Reset() {
	*x = GetSpendingInfoRequest{}
	mi := &file_proto_gpuproxy_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpendingInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpendingInfoRequest) ProtoMessage() {}

func (x *GetSpendingInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpuproxy_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpendingInfoRequest.ProtoReflect.Descriptor instead.
func (*GetSpendingInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_gpuproxy_proto_rawDescGZIP(), []int{20}
}

type SpendingWindow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Window        string                 `protobuf:"bytes,1,opt,name=window,proto3" json:"window,omitempty"` // e.g., "5min", "60min", "1440min"
	Spent         float64                `protobuf:"fixed64,2,opt,name=spent,proto3" json:"spent,omitempty"`
	Limit         float64                `protobuf:"fixed64,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Remaining     float64                `protobuf:"fixed64,4,opt,name=remaining,proto3" json:"remaining,omitempty"`
	Exceeded      bool                   `protobuf:"varint,5,opt,name=exceeded,proto3" json:"exceeded,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpendingWindow) Reset() {
	*x = SpendingWindow{}
	mi := &file_proto_gpuproxy_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpendingWindow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpendingWindow) ProtoMessage() {}

func (x *SpendingWindow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpuproxy_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpendingWindow.ProtoReflect.Descriptor instead.
func (*SpendingWindow) Descriptor() ([]byte, []int) {
	return file_proto_gpuproxy_proto_rawDescGZIP(), []int{21}
}

func (x *SpendingWindow) GetWindow() string {
	if x != nil {
		return x.Window
	}
	return ""
}

func (x *SpendingWindow) GetSpent() float64 {
	if x != nil {
		return x.Spent
	}
	return 0
}

func (x *SpendingWindow) GetLimit() float64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SpendingWindow) GetRemaining() float64 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *SpendingWindow) GetExceeded() bool {
	if x != nil {
		return x.Exceeded
	}
	return false
}

type GetSpendingInfoResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Windows           []*SpendingWindow      `protobuf:"bytes,1,rep,name=windows,proto3" json:"windows,omitempty"`
	GuardRailsEnabled bool                   `protobuf:"varint,2,opt,name=guard_rails_enabled,json=guardRailsEnabled,proto3" json:"guard_rails_enabled,omitempty"`
	TotalSpent_24H    float64                `protobuf:"fixed64,3,opt,name=total_spent_24h,json=totalSpent24h,proto3" json:"total_spent_24h,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetSpendingInfoResponse) Reset() {
	*x = GetSpendingInfoResponse{}
	mi := &file_proto_gpuproxy_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpendingInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpendingInfoResponse) ProtoMessage() {}

func (x *GetSpendingInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpuproxy_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpendingInfoResponse.ProtoReflect.Descriptor instead.
func (*GetSpendingInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_gpuproxy_proto_rawDescGZIP(), []int{22}
}

func (x *GetSpendingInfoResponse) GetWindows() []*SpendingWindow {
	if x != nil {
		return x.Windows
	}
	return nil
}

func (x *GetSpendingInfoResponse) GetGuardRailsEnabled() bool {
	if x != nil {
		return x.GuardRailsEnabled
	}
	return false
}

func (x *GetSpendingInfoResponse) GetTotalSpent_24H() float64 {
	if x != nil {
		return x.TotalSpent_24H
	}
	return 0
}

type CheckSpendingLimitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckSpendingLimitRequest) Reset() {
	*x = CheckSpendingLimitRequest{}
	mi := &file_proto_gpuproxy_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSpendingLimitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSpendingLimitRequest) ProtoMessage() {}

func (x *CheckSpendingLimitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpuproxy_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSpendingLimitRequest.ProtoReflect.Descriptor instead.
func (*CheckSpendingLimitRequest) Descriptor() ([]byte, []int) {
	return file_proto_gpuproxy_proto_rawDescGZIP(), []int{23}
}

func (x *CheckSpendingLimitRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CheckSpendingLimitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	WouldExceed   []*SpendingWindow      `protobuf:"bytes,3,rep,name=would_exceed,json=wouldExceed,proto3" json:"would_exceed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckSpendingLimitResponse) Reset() {
	*x = CheckSpendingLimitResponse{}
	mi := &file_proto_gpuproxy_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSpendingLimitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSpendingLimitResponse) ProtoMessage() {}

func (x *CheckSpendingLimitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpuproxy_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSpendingLimitResponse.ProtoReflect.Descriptor instead.
func (*CheckSpendingLimitResponse) Descriptor() ([]byte, []int) {
	return file_proto_gpuproxy_proto_rawDescGZIP(), []int{24}
}

func (x *CheckSpendingLimitResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckSpendingLimitResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CheckSpendingLimitResponse) GetWouldExceed() []*SpendingWindow {
	if x != nil {
		return x.WouldExceed
	}
	return nil
}

// Load Balancing Messages
type SetLoadBalancerStrategyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Strategy      string                 `protobuf:"bytes,1,opt,name=strategy,proto3" json:"strategy,omitempty"` // "round_robin", "equal_weighted", "weighted_round_robin", "least_connections", "least_response_time"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLoadBalancerStrategyRequest) Reset() {
	*x = SetLoadBalancerStrategyRequest{}
	mi := &file_proto_gpuproxy_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLoadBalancerStrategyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLoadBalancerStrategyRequest) ProtoMessage() {}

func (x *SetLoadBalancerStrategyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpuproxy_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLoadBalancerStrategyRequest.ProtoReflect.Descriptor instead.
func (*SetLoadBalancerStrategyRequest) Descriptor() ([]byte, []int) {
	return file_proto_gpuproxy_proto_rawDescGZIP(), []int{25}
}

func (x *SetLoadBalancerStrategyRequest) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

type SetLoadBalancerStrategyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Strategy      string                 `protobuf:"bytes,1,opt,name=strategy,proto3" json:"strategy,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLoadBalancerStrategyResponse) Reset() {
	*x = SetLoadBalancerStrategyResponse{}
	mi := &file_proto_gpuproxy_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLoadBalancerStrategyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLoadBalancerStrategyResponse) ProtoMessage() {}

func (x *SetLoadBalancerStrategyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpuproxy_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLoadBalancerStrategyResponse.ProtoReflect.Descriptor instead.
func (*SetLoadBalancerStrategyResponse) Descriptor() ([]byte, []int) {
	return file_proto_gpuproxy_proto_rawDescGZIP(), []int{26}
}

func (x *SetLoadBalancerStrategyResponse) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *SetLoadBalancerStrategyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetLoadInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "server", "provider", or "all"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoadInfoRequest) Reset() {
	*x = GetLoadInfoRequest{}
	mi := &file_proto_gpuproxy_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoadInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoadInfoRequest) ProtoMessage() {}

func (x *GetLoadInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpuproxy_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoadInfoRequest.ProtoReflect.Descriptor instead.
func (*GetLoadInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_gpuproxy_proto_rawDescGZIP(), []int{27}
}

func (x *GetLoadInfoRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type LoadInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	InstanceId        string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Provider          string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Connections       int32                  `protobuf:"varint,3,opt,name=connections,proto3" json:"connections,omitempty"`
	AvgResponseTimeMs float64                `protobuf:"fixed64,4,opt,name=avg_response_time_ms,json=avgResponseTimeMs,proto3" json:"avg_response_time_ms,omitempty"`
	LoadScore         float64                `protobuf:"fixed64,5,opt,name=load_score,json=loadScore,proto3" json:"load_score,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LoadInfo) Reset() {
	*x = LoadInfo{}
	mi := &file_proto_gpuproxy_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadInfo) ProtoMessage() {}

func (x *LoadInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpuproxy_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadInfo.ProtoReflect.Descriptor instead.
func (*LoadInfo) Descriptor() ([]byte, []int) {
	return file_proto_gpuproxy_proto_rawDescGZIP(), []int{28}
}

func (x *LoadInfo) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *LoadInfo) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *LoadInfo) GetConnections() int32 {
	if x != nil {
		return x.Connections
	}
	return 0
}

func (x *LoadInfo) GetAvgResponseTimeMs() float64 {
	if x != nil {
		return x.AvgResponseTimeMs
	}
	return 0
}

func (x *LoadInfo) GetLoadScore() float64 {
	if x != nil {
		return x.LoadScore
	}
	return 0
}

type GetLoadInfoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServerLoad      []*LoadInfo            `protobuf:"bytes,1,rep,name=server_load,json=serverLoad,proto3" json:"server_load,omitempty"`
	ProviderLoad    []*LoadInfo            `protobuf:"bytes,2,rep,name=provider_load,json=providerLoad,proto3" json:"provider_load,omitempty"`
	CurrentStrategy string                 `protobuf:"bytes,3,opt,name=current_strategy,json=currentStrategy,proto3" json:"current_strategy,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetLoadInfoResponse) Reset() {
	*x = GetLoadInfoResponse{}
	mi := &file_proto_gpuproxy_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoadInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoadInfoResponse) ProtoMessage() {}

func (x *GetLoadInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpuproxy_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoadInfoResponse.ProtoReflect.Descriptor instead.
func (*GetLoadInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_gpuproxy_proto_rawDescGZIP(), []int{29}
}

func (x *GetLoadInfoResponse) GetServerLoad() []*LoadInfo {
	if x != nil {
		return x.ServerLoad
	}
	return nil
}

func (x *GetLoadInfoResponse) GetProviderLoad() []*LoadInfo {
	if x != nil {
		return x.ProviderLoad
	}
	return nil
}

func (x *GetLoadInfoResponse) GetCurrentStrategy() string {
	if x != nil {
		return x.CurrentStrategy
	}
	return ""
}

type ReserveGPUsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"` // 1-16
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	MinVram       float64                `protobuf:"fixed64,3,opt,name=min_vram,json=minVram,proto3" json:"min_vram,omitempty"`
	MaxPrice      float64                `protobuf:"fixed64,4,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveGPUsRequest) Reset() {
	*x = ReserveGPUsRequest{}
	mi := &file_proto_gpuproxy_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveGPUsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveGPUsRequest) ProtoMessage() {}

func (x *ReserveGPUsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpuproxy_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveGPUsRequest.ProtoReflect.Descriptor instead.
func (*ReserveGPUsRequest) Descriptor() ([]byte, []int) {
	return file_proto_gpuproxy_proto_rawDescGZIP(), []int{30}
}

func (x *ReserveGPUsRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ReserveGPUsRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ReserveGPUsRequest) GetMinVram() float64 {
	if x != nil {
		return x.MinVram
	}
	return 0
}

func (x *ReserveGPUsRequest) GetMaxPrice() float64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

type ReserveGPUsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ReservedInstances []*GPUInstance         `protobuf:"bytes,1,rep,name=reserved_instances,json=reservedInstances,proto3" json:"reserved_instances,omitempty"`
	ReservedCount     int32                  `protobuf:"varint,2,opt,name=reserved_count,json=reservedCount,proto3" json:"reserved_count,omitempty"`
	Message           string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReserveGPUsResponse) Reset() {
	*x = ReserveGPUsResponse{}
	mi := &file_proto_gpuproxy_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveGPUsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveGPUsResponse) ProtoMessage() {}

func (x *ReserveGPUsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpuproxy_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveGPUsResponse.ProtoReflect.Descriptor instead.
func (*ReserveGPUsResponse) Descriptor() ([]byte, []int) {
	return file_proto_gpuproxy_proto_rawDescGZIP(), []int{31}
}

func (x *ReserveGPUsResponse) GetReservedInstances() []*GPUInstance {
	if x != nil {
		return x.ReservedInstances
	}
	return nil
}

func (x *ReserveGPUsResponse) GetReservedCount() int32 {
	if x != nil {
		return x.ReservedCount
	}
	return 0
}

func (x *ReserveGPUsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// CUIC Protocol Messages
type CUICMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StreamId       string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	MessageId      string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Version        string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Sender         string                 `protobuf:"bytes,4,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver       string                 `protobuf:"bytes,5,opt,name=receiver,proto3" json:"receiver,omitempty"`
	MessageType    string                 `protobuf:"bytes,6,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"` // "stream", "datagram", "request", "response", "control", "heartbeat"
	Priority       int32                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`                         // 0-255, higher = more urgent
	Timestamp      int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload        []byte                 `protobuf:"bytes,9,opt,name=payload,proto3" json:"payload,omitempty"` // JSON-encoded payload
	Metadata       map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CongestionHint string                 `protobuf:"bytes,11,opt,name=congestion_hint,json=congestionHint,proto3" json:"congestion_hint,omitempty"` // "none", "moderate", "severe"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CUICMessageRequest) Reset() {
	*x = CUICMessageRequest{}
	mi := &file_proto_gpuproxy_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CUICMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CUICMessageRequest) ProtoMessage() {}

func (x *CUICMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpuproxy_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CUICMessageRequest.ProtoReflect.Descriptor instead.
func (*CUICMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_gpuproxy_proto_rawDescGZIP(), []int{32}
}

func (x *CUICMessageRequest) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *CUICMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *CUICMessageRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CUICMessageRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *CUICMessageRequest) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *CUICMessageRequest) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *CUICMessageRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *CUICMessageRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CUICMessageRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CUICMessageRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CUICMessageRequest) GetCongestionHint() string {
	if x != nil {
		return x.CongestionHint
	}
	return ""
}

type CUICMessageResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StreamId       string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	MessageId      string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	InReplyTo      string                 `protobuf:"bytes,3,opt,name=in_reply_to,json=inReplyTo,proto3" json:"in_reply_to,omitempty"`
	Version        string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Sender         string                 `protobuf:"bytes,5,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver       string                 `protobuf:"bytes,6,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Status         *CUICStatus            `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Payload        []byte                 `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"` // JSON-encoded payload
	Timestamp      int64                  `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CongestionHint string                 `protobuf:"bytes,11,opt,name=congestion_hint,json=congestionHint,proto3" json:"congestion_hint,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CUICMessageResponse) Reset() {
	*x = CUICMessageResponse{}
	mi := &file_proto_gpuproxy_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CUICMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CUICMessageResponse) ProtoMessage() {}

func (x *CUICMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpuproxy_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CUICMessageResponse.ProtoReflect.Descriptor instead.
func (*CUICMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_gpuproxy_proto_rawDescGZIP(), []int{33}
}

func (x *CUICMessageResponse) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *CUICMessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *CUICMessageResponse) GetInReplyTo() string {
	if x != nil {
		return x.InReplyTo
	}
	return ""
}

func (x *CUICMessageResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CUICMessageResponse) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *CUICMessageResponse) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *CUICMessageResponse) GetStatus() *CUICStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *CUICMessageResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *CUICMessageResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CUICMessageResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CUICMessageResponse) GetCongestionHint() string {
	if x != nil {
		return x.CongestionHint
	}
	return ""
}

type CUICStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Retriable     bool                   `protobuf:"varint,4,opt,name=retriable,proto3" json:"retriable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CUICStatus) Reset() {
	*x = CUICStatus{}
	mi := &file_proto_gpuproxy_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CUICStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CUICStatus) ProtoMessage() {}

func (x *CUICStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpuproxy_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CUICStatus.ProtoReflect.Descriptor instead.
func (*CUICStatus) Descriptor() ([]byte, []int) {
	return file_proto_gpuproxy_proto_rawDescGZIP(), []int{34}
}

func (x *CUICStatus) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CUICStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CUICStatus) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CUICStatus) GetRetriable() bool {
	if x != nil {
		return x.Retriable
	}
	return false
}

// Health Check Messages
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_gpuproxy_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpuproxy_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_gpuproxy_proto_rawDescGZIP(), []int{35}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_gpuproxy_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gpuproxy_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_gpuproxy_proto_rawDescGZIP(), []int{36}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HealthCheckResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_proto_gpuproxy_proto protoreflect.FileDescriptor

const file_proto_gpuproxy_proto_rawDesc = "" +
	"\n" +
	"\x14proto/gpuproxy.proto\x12\bgpuproxy\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"T\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"?\n" +
	"\x13CreateAPIKeyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"b\n" +
	"\x14CreateAPIKeyResponse\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\"\x8a\x01\n" +
	"\x17ListGPUInstancesRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x19\n" +
	"\bmin_vram\x18\x02 \x01(\x01R\aminVram\x12\x1b\n" +
	"\tmax_price\x18\x03 \x01(\x01R\bmaxPrice\x12\x1b\n" +
	"\tgpu_model\x18\x04 \x01(\tR\bgpuModel\"\xe2\x02\n" +
	"\vGPUInstance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12$\n" +
	"\x0eprice_per_hour\x18\x04 \x01(\x01R\fpricePerHour\x12\x17\n" +
	"\avram_gb\x18\x05 \x01(\x05R\x06vramGb\x12\x1b\n" +
	"\tgpu_model\x18\x06 \x01(\tR\bgpuModel\x12\x19\n" +
	"\bnum_gpus\x18\a \x01(\x05R\anumGpus\x12\x1a\n" +
	"\blocation\x18\b \x01(\tR\blocation\x12?\n" +
	"\bmetadata\x18\t \x03(\v2#.gpuproxy.GPUInstance.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"p\n" +
	"\x18ListGPUInstancesResponse\x123\n" +
	"\tinstances\x18\x01 \x03(\v2\x15.gpuproxy.GPUInstanceR\tinstances\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\xfa\x01\n" +
	"\x18CreateGPUInstanceRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12=\n" +
	"\x03env\x18\x04 \x03(\v2+.gpuproxy.CreateGPUInstanceRequest.EnvEntryR\x03env\x12\x14\n" +
	"\x05ports\x18\x05 \x03(\x05R\x05ports\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8a\x01\n" +
	"\x19CreateGPUInstanceResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"X\n" +
	"\x19DestroyGPUInstanceRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\"P\n" +
	"\x1aDestroyGPUInstanceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"T\n" +
	"\x15GetGPUInstanceRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\"K\n" +
	"\x16GetGPUInstanceResponse\x121\n" +
	"\binstance\x18\x01 \x01(\v2\x15.gpuproxy.GPUInstanceR\binstance\"\x98\x02\n" +
	"\x13ProxyRequestMessage\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x1d\n" +
	"\n" +
	"target_url\x18\x02 \x01(\tR\ttargetUrl\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12D\n" +
	"\aheaders\x18\x04 \x03(\v2*.gpuproxy.ProxyRequestMessage.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x05 \x01(\fR\x04body\x12\x18\n" +
	"\atimeout\x18\x06 \x01(\x05R\atimeout\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd6\x01\n" +
	"\rProxyResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12>\n" +
	"\aheaders\x18\x02 \x03(\v2$.gpuproxy.ProxyResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8d\x01\n" +
	"\x14CreatePaymentRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12%\n" +
	"\x0epayment_method\x18\x04 \x01(\tR\rpaymentMethod\"\x82\x01\n" +
	"\x15CreatePaymentResponse\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"F\n" +
	"\x16GetTransactionsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"\xbd\x01\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\"u\n" +
	"\x17GetTransactionsResponse\x129\n" +
	"\ftransactions\x18\x01 \x03(\v2\x15.gpuproxy.TransactionR\ftransactions\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\x18\n" +
	"\x16GetSpendingInfoRequest\"\x8e\x01\n" +
	"\x0eSpendingWindow\x12\x16\n" +
	"\x06window\x18\x01 \x01(\tR\x06window\x12\x14\n" +
	"\x05spent\x18\x02 \x01(\x01R\x05spent\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x01R\x05limit\x12\x1c\n" +
	"\tremaining\x18\x04 \x01(\x01R\tremaining\x12\x1a\n" +
	"\bexceeded\x18\x05 \x01(\bR\bexceeded\"\xa5\x01\n" +
	"\x17GetSpendingInfoResponse\x122\n" +
	"\awindows\x18\x01 \x03(\v2\x18.gpuproxy.SpendingWindowR\awindows\x12.\n" +
	"\x13guard_rails_enabled\x18\x02 \x01(\bR\x11guardRailsEnabled\x12&\n" +
	"\x0ftotal_spent_24h\x18\x03 \x01(\x01R\rtotalSpent24h\"3\n" +
	"\x19CheckSpendingLimitRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\"\x8b\x01\n" +
	"\x1aCheckSpendingLimitResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12;\n" +
	"\fwould_exceed\x18\x03 \x03(\v2\x18.gpuproxy.SpendingWindowR\vwouldExceed\"<\n" +
	"\x1eSetLoadBalancerStrategyRequest\x12\x1a\n" +
	"\bstrategy\x18\x01 \x01(\tR\bstrategy\"W\n" +
	"\x1fSetLoadBalancerStrategyResponse\x12\x1a\n" +
	"\bstrategy\x18\x01 \x01(\tR\bstrategy\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"(\n" +
	"\x12GetLoadInfoRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\"\xb9\x01\n" +
	"\bLoadInfo\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12 \n" +
	"\vconnections\x18\x03 \x01(\x05R\vconnections\x12/\n" +
	"\x14avg_response_time_ms\x18\x04 \x01(\x01R\x11avgResponseTimeMs\x12\x1d\n" +
	"\n" +
	"load_score\x18\x05 \x01(\x01R\tloadScore\"\xae\x01\n" +
	"\x13GetLoadInfoResponse\x123\n" +
	"\vserver_load\x18\x01 \x03(\v2\x12.gpuproxy.LoadInfoR\n" +
	"serverLoad\x127\n" +
	"\rprovider_load\x18\x02 \x03(\v2\x12.gpuproxy.LoadInfoR\fproviderLoad\x12)\n" +
	"\x10current_strategy\x18\x03 \x01(\tR\x0fcurrentStrategy\"~\n" +
	"\x12ReserveGPUsRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x19\n" +
	"\bmin_vram\x18\x03 \x01(\x01R\aminVram\x12\x1b\n" +
	"\tmax_price\x18\x04 \x01(\x01R\bmaxPrice\"\x9c\x01\n" +
	"\x13ReserveGPUsResponse\x12D\n" +
	"\x12reserved_instances\x18\x01 \x03(\v2\x15.gpuproxy.GPUInstanceR\x11reservedInstances\x12%\n" +
	"\x0ereserved_count\x18\x02 \x01(\x05R\rreservedCount\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xc3\x03\n" +
	"\x12CUICMessageRequest\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x16\n" +
	"\x06sender\x18\x04 \x01(\tR\x06sender\x12\x1a\n" +
	"\breceiver\x18\x05 \x01(\tR\breceiver\x12!\n" +
	"\fmessage_type\x18\x06 \x01(\tR\vmessageType\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriority\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\x12\x18\n" +
	"\apayload\x18\t \x01(\fR\apayload\x12F\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2*.gpuproxy.CUICMessageRequest.MetadataEntryR\bmetadata\x12'\n" +
	"\x0fcongestion_hint\x18\v \x01(\tR\x0econgestionHint\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd4\x03\n" +
	"\x13CUICMessageResponse\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x1e\n" +
	"\vin_reply_to\x18\x03 \x01(\tR\tinReplyTo\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x16\n" +
	"\x06sender\x18\x05 \x01(\tR\x06sender\x12\x1a\n" +
	"\breceiver\x18\x06 \x01(\tR\breceiver\x12,\n" +
	"\x06status\x18\a \x01(\v2\x14.gpuproxy.CUICStatusR\x06status\x12\x18\n" +
	"\apayload\x18\b \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\t \x01(\x03R\ttimestamp\x12G\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2+.gpuproxy.CUICMessageResponse.MetadataEntryR\bmetadata\x12'\n" +
	"\x0fcongestion_hint\x18\v \x01(\tR\x0econgestionHint\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"r\n" +
	"\n" +
	"CUICStatus\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x1c\n" +
	"\tretriable\x18\x04 \x01(\bR\tretriable\"\x14\n" +
	"\x12HealthCheckRequest\"\xcd\x01\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12D\n" +
	"\adetails\x18\x03 \x03(\v2*.gpuproxy.HealthCheckResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x80\f\n" +
	"\x0fGPUProxyService\x128\n" +
	"\x05Login\x12\x16.gpuproxy.LoginRequest\x1a\x17.gpuproxy.LoginResponse\x12M\n" +
	"\fCreateAPIKey\x12\x1d.gpuproxy.CreateAPIKeyRequest\x1a\x1e.gpuproxy.CreateAPIKeyResponse\x12Y\n" +
	"\x10ListGPUInstances\x12!.gpuproxy.ListGPUInstancesRequest\x1a\".gpuproxy.ListGPUInstancesResponse\x12\\\n" +
	"\x11CreateGPUInstance\x12\".gpuproxy.CreateGPUInstanceRequest\x1a#.gpuproxy.CreateGPUInstanceResponse\x12_\n" +
	"\x12DestroyGPUInstance\x12#.gpuproxy.DestroyGPUInstanceRequest\x1a$.gpuproxy.DestroyGPUInstanceResponse\x12S\n" +
	"\x0eGetGPUInstance\x12\x1f.gpuproxy.GetGPUInstanceRequest\x1a .gpuproxy.GetGPUInstanceResponse\x12F\n" +
	"\fProxyRequest\x12\x1d.gpuproxy.ProxyRequestMessage\x1a\x17.gpuproxy.ProxyResponse\x12P\n" +
	"\x12StreamProxyRequest\x12\x1d.gpuproxy.ProxyRequestMessage\x1a\x17.gpuproxy.ProxyResponse(\x010\x01\x12P\n" +
	"\rCreatePayment\x12\x1e.gpuproxy.CreatePaymentRequest\x1a\x1f.gpuproxy.CreatePaymentResponse\x12V\n" +
	"\x0fGetTransactions\x12 .gpuproxy.GetTransactionsRequest\x1a!.gpuproxy.GetTransactionsResponse\x12V\n" +
	"\x0fGetSpendingInfo\x12 .gpuproxy.GetSpendingInfoRequest\x1a!.gpuproxy.GetSpendingInfoResponse\x12_\n" +
	"\x12CheckSpendingLimit\x12#.gpuproxy.CheckSpendingLimitRequest\x1a$.gpuproxy.CheckSpendingLimitResponse\x12n\n" +
	"\x17SetLoadBalancerStrategy\x12(.gpuproxy.SetLoadBalancerStrategyRequest\x1a).gpuproxy.SetLoadBalancerStrategyResponse\x12J\n" +
	"\vGetLoadInfo\x12\x1c.gpuproxy.GetLoadInfoRequest\x1a\x1d.gpuproxy.GetLoadInfoResponse\x12J\n" +
	"\vReserveGPUs\x12\x1c.gpuproxy.ReserveGPUsRequest\x1a\x1d.gpuproxy.ReserveGPUsResponse\x12N\n" +
	"\x0fSendCUICMessage\x12\x1c.gpuproxy.CUICMessageRequest\x1a\x1d.gpuproxy.CUICMessageResponse\x12T\n" +
	"\x11StreamCUICMessage\x12\x1c.gpuproxy.CUICMessageRequest\x1a\x1d.gpuproxy.CUICMessageResponse(\x010\x01\x12J\n" +
	"\vHealthCheck\x12\x1c.gpuproxy.HealthCheckRequest\x1a\x1d.gpuproxy.HealthCheckResponseB)Z'github.com/aiserve/gpuproxy/pkg/grpc/pbb\x06proto3"

var (
	file_proto_gpuproxy_proto_rawDescOnce sync.Once
	file_proto_gpuproxy_proto_rawDescData []byte
)

func file_proto_gpuproxy_proto_rawDescGZIP() []byte {
	file_proto_gpuproxy_proto_rawDescOnce.Do(func() {
		file_proto_gpuproxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gpuproxy_proto_rawDesc), len(file_proto_gpuproxy_proto_rawDesc)))
	})
	return file_proto_gpuproxy_proto_rawDescData
}

var file_proto_gpuproxy_proto_msgTypes = make([]protoimpl.MessageInfo, 44)
var file_proto_gpuproxy_proto_goTypes = []any{
	(*LoginRequest)(nil),                    // 0: gpuproxy.LoginRequest
	(*LoginResponse)(nil),                   // 1: gpuproxy.LoginResponse
	(*CreateAPIKeyRequest)(nil),             // 2: gpuproxy.CreateAPIKeyRequest
	(*CreateAPIKeyResponse)(nil),            // 3: gpuproxy.CreateAPIKeyResponse
	(*ListGPUInstancesRequest)(nil),         // 4: gpuproxy.ListGPUInstancesRequest
	(*GPUInstance)(nil),                     // 5: gpuproxy.GPUInstance
	(*ListGPUInstancesResponse)(nil),        // 6: gpuproxy.ListGPUInstancesResponse
	(*CreateGPUInstanceRequest)(nil),        // 7: gpuproxy.CreateGPUInstanceRequest
	(*CreateGPUInstanceResponse)(nil),       // 8: gpuproxy.CreateGPUInstanceResponse
	(*DestroyGPUInstanceRequest)(nil),       // 9: gpuproxy.DestroyGPUInstanceRequest
	(*DestroyGPUInstanceResponse)(nil),      // 10: gpuproxy.DestroyGPUInstanceResponse
	(*GetGPUInstanceRequest)(nil),           // 11: gpuproxy.GetGPUInstanceRequest
	(*GetGPUInstanceResponse)(nil),          // 12: gpuproxy.GetGPUInstanceResponse
	(*ProxyRequestMessage)(nil),             // 13: gpuproxy.ProxyRequestMessage
	(*ProxyResponse)(nil),                   // 14: gpuproxy.ProxyResponse
	(*CreatePaymentRequest)(nil),            // 15: gpuproxy.CreatePaymentRequest
	(*CreatePaymentResponse)(nil),           // 16: gpuproxy.CreatePaymentResponse
	(*GetTransactionsRequest)(nil),          // 17: gpuproxy.GetTransactionsRequest
	(*Transaction)(nil),                     // 18: gpuproxy.Transaction
	(*GetTransactionsResponse)(nil),         // 19: gpuproxy.GetTransactionsResponse
	(*GetSpendingInfoRequest)(nil),          // 20: gpuproxy.GetSpendingInfoRequest
	(*SpendingWindow)(nil),                  // 21: gpuproxy.SpendingWindow
	(*GetSpendingInfoResponse)(nil),         // 22: gpuproxy.GetSpendingInfoResponse
	(*CheckSpendingLimitRequest)(nil),       // 23: gpuproxy.CheckSpendingLimitRequest
	(*CheckSpendingLimitResponse)(nil),      // 24: gpuproxy.CheckSpendingLimitResponse
	(*SetLoadBalancerStrategyRequest)(nil),  // 25: gpuproxy.SetLoadBalancerStrategyRequest
	(*SetLoadBalancerStrategyResponse)(nil), // 26: gpuproxy.SetLoadBalancerStrategyResponse
	(*GetLoadInfoRequest)(nil),              // 27: gpuproxy.GetLoadInfoRequest
	(*LoadInfo)(nil),                        // 28: gpuproxy.LoadInfo
	(*GetLoadInfoResponse)(nil),             // 29: gpuproxy.GetLoadInfoResponse
	(*ReserveGPUsRequest)(nil),              // 30: gpuproxy.ReserveGPUsRequest
	(*ReserveGPUsResponse)(nil),             // 31: gpuproxy.ReserveGPUsResponse
	(*CUICMessageRequest)(nil),              // 32: gpuproxy.CUICMessageRequest
	(*CUICMessageResponse)(nil),             // 33: gpuproxy.CUICMessageResponse
	(*CUICStatus)(nil),                      // 34: gpuproxy.CUICStatus
	(*HealthCheckRequest)(nil),              // 35: gpuproxy.HealthCheckRequest
	(*HealthCheckResponse)(nil),             // 36: gpuproxy.HealthCheckResponse
	nil,                                     // 37: gpuproxy.GPUInstance.MetadataEntry
	nil,                                     // 38: gpuproxy.CreateGPUInstanceRequest.EnvEntry
	nil,                                     // 39: gpuproxy.ProxyRequestMessage.HeadersEntry
	nil,                                     // 40: gpuproxy.ProxyResponse.HeadersEntry
	nil,                                     // 41: gpuproxy.CUICMessageRequest.MetadataEntry
	nil,                                     // 42: gpuproxy.CUICMessageResponse.MetadataEntry
	nil,                                     // 43: gpuproxy.HealthCheckResponse.DetailsEntry
}
var file_proto_gpuproxy_proto_depIdxs = []int32{
	37, // 0: gpuproxy.GPUInstance.metadata:type_name -> gpuproxy.GPUInstance.MetadataEntry
	5,  // 1: gpuproxy.ListGPUInstancesResponse.instances:type_name -> gpuproxy.GPUInstance
	38, // 2: gpuproxy.CreateGPUInstanceRequest.env:type_name -> gpuproxy.CreateGPUInstanceRequest.EnvEntry
	5,  // 3: gpuproxy.GetGPUInstanceResponse.instance:type_name -> gpuproxy.GPUInstance
	39, // 4: gpuproxy.ProxyRequestMessage.headers:type_name -> gpuproxy.ProxyRequestMessage.HeadersEntry
	40, // 5: gpuproxy.ProxyResponse.headers:type_name -> gpuproxy.ProxyResponse.HeadersEntry
	18, // 6: gpuproxy.GetTransactionsResponse.transactions:type_name -> gpuproxy.Transaction
	21, // 7: gpuproxy.GetSpendingInfoResponse.windows:type_name -> gpuproxy.SpendingWindow
	21, // 8: gpuproxy.CheckSpendingLimitResponse.would_exceed:type_name -> gpuproxy.SpendingWindow
	28, // 9: gpuproxy.GetLoadInfoResponse.server_load:type_name -> gpuproxy.LoadInfo
	28, // 10: gpuproxy.GetLoadInfoResponse.provider_load:type_name -> gpuproxy.LoadInfo
	5,  // 11: gpuproxy.ReserveGPUsResponse.reserved_instances:type_name -> gpuproxy.GPUInstance
	41, // 12: gpuproxy.CUICMessageRequest.metadata:type_name -> gpuproxy.CUICMessageRequest.MetadataEntry
	34, // 13: gpuproxy.CUICMessageResponse.status:type_name -> gpuproxy.CUICStatus
	42, // 14: gpuproxy.CUICMessageResponse.metadata:type_name -> gpuproxy.CUICMessageResponse.MetadataEntry
	43, // 15: gpuproxy.HealthCheckResponse.details:type_name -> gpuproxy.HealthCheckResponse.DetailsEntry
	0,  // 16: gpuproxy.GPUProxyService.Login:input_type -> gpuproxy.LoginRequest
	2,  // 17: gpuproxy.GPUProxyService.CreateAPIKey:input_type -> gpuproxy.CreateAPIKeyRequest
	4,  // 18: gpuproxy.GPUProxyService.ListGPUInstances:input_type -> gpuproxy.ListGPUInstancesRequest
	7,  // 19: gpuproxy.GPUProxyService.CreateGPUInstance:input_type -> gpuproxy.CreateGPUInstanceRequest
	9,  // 20: gpuproxy.GPUProxyService.DestroyGPUInstance:input_type -> gpuproxy.DestroyGPUInstanceRequest
	11, // 21: gpuproxy.GPUProxyService.GetGPUInstance:input_type -> gpuproxy.GetGPUInstanceRequest
	13, // 22: gpuproxy.GPUProxyService.ProxyRequest:input_type -> gpuproxy.ProxyRequestMessage
	13, // 23: gpuproxy.GPUProxyService.StreamProxyRequest:input_type -> gpuproxy.ProxyRequestMessage
	15, // 24: gpuproxy.GPUProxyService.CreatePayment:input_type -> gpuproxy.CreatePaymentRequest
	17, // 25: gpuproxy.GPUProxyService.GetTransactions:input_type -> gpuproxy.GetTransactionsRequest
	20, // 26: gpuproxy.GPUProxyService.GetSpendingInfo:input_type -> gpuproxy.GetSpendingInfoRequest
	23, // 27: gpuproxy.GPUProxyService.CheckSpendingLimit:input_type -> gpuproxy.CheckSpendingLimitRequest
	25, // 28: gpuproxy.GPUProxyService.SetLoadBalancerStrategy:input_type -> gpuproxy.SetLoadBalancerStrategyRequest
	27, // 29: gpuproxy.GPUProxyService.GetLoadInfo:input_type -> gpuproxy.GetLoadInfoRequest
	30, // 30: gpuproxy.GPUProxyService.ReserveGPUs:input_type -> gpuproxy.ReserveGPUsRequest
	32, // 31: gpuproxy.GPUProxyService.SendCUICMessage:input_type -> gpuproxy.CUICMessageRequest
	32, // 32: gpuproxy.GPUProxyService.StreamCUICMessage:input_type -> gpuproxy.CUICMessageRequest
	35, // 33: gpuproxy.GPUProxyService.HealthCheck:input_type -> gpuproxy.HealthCheckRequest
	1,  // 34: gpuproxy.GPUProxyService.Login:output_type -> gpuproxy.LoginResponse
	3,  // 35: gpuproxy.GPUProxyService.CreateAPIKey:output_type -> gpuproxy.CreateAPIKeyResponse
	6,  // 36: gpuproxy.GPUProxyService.ListGPUInstances:output_type -> gpuproxy.ListGPUInstancesResponse
	8,  // 37: gpuproxy.GPUProxyService.CreateGPUInstance:output_type -> gpuproxy.CreateGPUInstanceResponse
	10, // 38: gpuproxy.GPUProxyService.DestroyGPUInstance:output_type -> gpuproxy.DestroyGPUInstanceResponse
	12, // 39: gpuproxy.GPUProxyService.GetGPUInstance:output_type -> gpuproxy.GetGPUInstanceResponse
	14, // 40: gpuproxy.GPUProxyService.ProxyRequest:output_type -> gpuproxy.ProxyResponse
	14, // 41: gpuproxy.GPUProxyService.StreamProxyRequest:output_type -> gpuproxy.ProxyResponse
	16, // 42: gpuproxy.GPUProxyService.CreatePayment:output_type -> gpuproxy.CreatePaymentResponse
	19, // 43: gpuproxy.GPUProxyService.GetTransactions:output_type -> gpuproxy.GetTransactionsResponse
	22, // 44: gpuproxy.GPUProxyService.GetSpendingInfo:output_type -> gpuproxy.GetSpendingInfoResponse
	24, // 45: gpuproxy.GPUProxyService.CheckSpendingLimit:output_type -> gpuproxy.CheckSpendingLimitResponse
	26, // 46: gpuproxy.GPUProxyService.SetLoadBalancerStrategy:output_type -> gpuproxy.SetLoadBalancerStrategyResponse
	29, // 47: gpuproxy.GPUProxyService.GetLoadInfo:output_type -> gpuproxy.GetLoadInfoResponse
	31, // 48: gpuproxy.GPUProxyService.ReserveGPUs:output_type -> gpuproxy.ReserveGPUsResponse
	33, // 49: gpuproxy.GPUProxyService.SendCUICMessage:output_type -> gpuproxy.CUICMessageResponse
	33, // 50: gpuproxy.GPUProxyService.StreamCUICMessage:output_type -> gpuproxy.CUICMessageResponse
	36, // 51: gpuproxy.GPUProxyService.HealthCheck:output_type -> gpuproxy.HealthCheckResponse
	34, // [34:52] is the sub-list for method output_type
	16, // [16:34] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_gpuproxy_proto_init() }
func file_proto_gpuproxy_proto_init() {
	if File_proto_gpuproxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gpuproxy_proto_rawDesc), len(file_proto_gpuproxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   44,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gpuproxy_proto_goTypes,
		DependencyIndexes: file_proto_gpuproxy_proto_depIdxs,
		MessageInfos:      file_proto_gpuproxy_proto_msgTypes,
	}.Build()
	File_proto_gpuproxy_proto = out.File
	file_proto_gpuproxy_proto_goTypes = nil
	file_proto_gpuproxy_proto_depIdxs = nil
}
